name: TaskIt
description: 'Mobile app of TaskIt'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  easy_date_timeline: ^2.0.4
  image_picker: ^1.1.2
  flutter_svg: ^1.1.6
  cloud_firestore: ^5.5.0
  provider: ^6.1.2
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pp_default.png
    - assets/logo.svg

platforms:
  android:
