// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEO67IDOMt6d69zsReDa7jvmjG3SFjTqQ',
    appId: '1:1084178538565:web:d18799a6bc2549660e432c',
    messagingSenderId: '1084178538565',
    projectId: 'test-c9086',
    authDomain: 'test-c9086.firebaseapp.com',
    storageBucket: 'test-c9086.firebasestorage.app',
    measurementId: 'G-269NEFBN14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSxLM4eGY_PL6i_AjCcy8BsNcnpWTAb_M',
    appId: '1:1084178538565:android:fc05a870c81b87780e432c',
    messagingSenderId: '1084178538565',
    projectId: 'test-c9086',
    storageBucket: 'test-c9086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJA4qyOrXCp2nE5B4DCA6JH5018Q4bRk8',
    appId: '1:1084178538565:ios:8ec13a2834456dcb0e432c',
    messagingSenderId: '1084178538565',
    projectId: 'test-c9086',
    storageBucket: 'test-c9086.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJA4qyOrXCp2nE5B4DCA6JH5018Q4bRk8',
    appId: '1:1084178538565:ios:8ec13a2834456dcb0e432c',
    messagingSenderId: '1084178538565',
    projectId: 'test-c9086',
    storageBucket: 'test-c9086.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEO67IDOMt6d69zsReDa7jvmjG3SFjTqQ',
    appId: '1:1084178538565:web:af8e1158b41ca8e50e432c',
    messagingSenderId: '1084178538565',
    projectId: 'test-c9086',
    authDomain: 'test-c9086.firebaseapp.com',
    storageBucket: 'test-c9086.firebasestorage.app',
    measurementId: 'G-BQ4LF94642',
  );
}
